---
- hosts: all
  become: true
  tasks:
    - name: Check for essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
      when: ansible_distribution == "Debian"

    - name: Update and upgrade the server
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

- hosts: zabbix_server
  become: true
  tasks:
    - name: Install Zabbix repository
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb
      notify:
        - Update apt cache

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix base packages
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
        update_cache: yes
      retries: 1
      delay: 5
      register: zabbix_installation
      until: zabbix_installation is succeeded

- hosts: zabbix_server
  become: true
  roles:
    - zabbix_mysql
    - zabbix_nginx
    - zabbix_settings

